use std::{
    collections::VecDeque,
    ffi::OsString,
    path::PathBuf,
    process::Child,
    sync::Arc,
    time::{Duration, Instant},
};

use smithay::{
    backend::input::{ButtonState, KeyState},
    desktop::{PopupManager, Space, Window, WindowSurfaceType},
    input::{Seat, SeatState},
    reexports::{
        calloop::{generic::Generic, EventLoop, Interest, LoopSignal, Mode, PostAction},
        wayland_protocols::xdg::shell::server::xdg_toplevel,
        wayland_server::{
            backend::{ClientData, ClientId, DisconnectReason},
            protocol::wl_surface::WlSurface,
            Display, DisplayHandle,
        },
    },
    utils::{Logical, Physical, Point, Rectangle, Size, SERIAL_COUNTER},
    wayland::{
        compositor::{CompositorClientState, CompositorState},
        output::OutputManagerState,
        selection::data_device::DataDeviceState,
        shell::xdg::XdgShellState,
        shm::ShmState,
        socket::ListeningSocketSource,
    },
};

use crate::{
    protocol::Protocol,
    window::{AutoWindowId, WindowRegistry},
};

pub struct AutoWC {
    pub start_time: std::time::Instant,
    pub socket_name: OsString,
    pub display_handle: DisplayHandle,

    pub space: Space<Window>,
    pub loop_signal: LoopSignal,
    pub virtual_size: Size<i32, Logical>,
    pub dynamic_resize: bool,
    pub windows: WindowRegistry,
    pub default_window_id: AutoWindowId,
    pub host_size: Size<i32, Physical>,
    pub pointer_in_viewport: bool,
    pub child: Option<Child>,
    pub stay_alive: bool,
    pub pending_screenshots: VecDeque<ScreenshotRequest>,
    pub control_queue: VecDeque<QueuedControlAction>,
    pub next_control_action_at: Option<Instant>,
    pub key_event_interval: Duration,
    pub chord_key_interval: Duration,
    pub chord_hold_duration: Duration,
    pub command_interval: Duration,
    pub protocol: Protocol,
    screenshot_counter: u64,
    autogenerated_screenshots: Vec<PathBuf>,

    // Smithay State
    pub compositor_state: CompositorState,
    pub xdg_shell_state: XdgShellState,
    pub shm_state: ShmState,
    pub output_manager_state: OutputManagerState,
    pub seat_state: SeatState<AutoWC>,
    pub data_device_state: DataDeviceState,
    pub popups: PopupManager,

    pub seat: Seat<Self>,
}

impl AutoWC {
    pub fn new(
        event_loop: &mut EventLoop<Self>,
        display: Display<Self>,
        virtual_size: Size<i32, Logical>,
        dynamic_resize: bool,
        stay_alive: bool,
        timing: TimingOptions,
        protocol: Protocol,
    ) -> Self {
        let start_time = std::time::Instant::now();

        let dh = display.handle();

        // Here we initialize implementations of some wayland protocols
        // Some of them require us to implement traits on the AutoWC state,
        // you can find those implementations in the `crate::handlers` module

        // Initialize protocols needed for displaying windows
        let compositor_state = CompositorState::new::<Self>(&dh);
        let xdg_shell_state = XdgShellState::new::<Self>(&dh);
        let shm_state = ShmState::new::<Self>(&dh, vec![]);
        let popups = PopupManager::default();

        let output_manager_state = OutputManagerState::new_with_xdg_output::<Self>(&dh);

        // Data device is responsible for clipboard and drag-and-drop
        let data_device_state = DataDeviceState::new::<Self>(&dh);

        // A seat is a group of keyboards, pointer and touch devices.
        // A seat typically has a pointer and maintains a keyboard focus and a pointer focus.
        let mut seat_state = SeatState::new();
        let mut seat: Seat<Self> = seat_state.new_wl_seat(&dh, "winit");

        // Notify clients that we have a keyboard, for the sake of the example we assume that keyboard is always present.
        // You may want to track keyboard hot-plug in real compositor.
        seat.add_keyboard(Default::default(), 200, 25).unwrap();

        // Notify clients that we have a pointer (mouse)
        // Here we assume that there is always pointer plugged in
        seat.add_pointer();

        // A space represents a two-dimensional plane. Windows and Outputs can be mapped onto it.
        //
        // Windows get a position and stacking order through mapping.
        // Outputs become views of a part of the Space and can be rendered via Space::render_output.
        let space = Space::default();

        // Setup a wayland socket that will be used to accept clients
        let socket_name = Self::init_wayland_listener(display, event_loop);

        // Get the loop signal, used to stop the event loop
        let loop_signal = event_loop.get_signal();

        let mut windows = WindowRegistry::new();
        let default_window_id = windows.create_window();

        Self {
            start_time,
            display_handle: dh,

            space,
            loop_signal,
            socket_name,
            virtual_size,
            dynamic_resize,
            windows,
            default_window_id,
            host_size: virtual_size.to_physical(1),
            pointer_in_viewport: false,
            child: None,
            stay_alive,
            pending_screenshots: VecDeque::new(),
            control_queue: VecDeque::new(),
            next_control_action_at: None,
            key_event_interval: timing.key_event_interval,
            chord_key_interval: timing.chord_key_interval,
            chord_hold_duration: timing.chord_hold_duration,
            command_interval: timing.command_interval,
            protocol,
            screenshot_counter: 0,
            autogenerated_screenshots: Vec::new(),

            compositor_state,
            xdg_shell_state,
            shm_state,
            output_manager_state,
            seat_state,
            data_device_state,
            popups,
            seat,
        }
    }

    fn init_wayland_listener(
        display: Display<AutoWC>,
        event_loop: &mut EventLoop<Self>,
    ) -> OsString {
        // Creates a new listening socket, automatically choosing the next available `wayland` socket name.
        let listening_socket = ListeningSocketSource::new_auto().unwrap();

        // Get the name of the listening socket.
        // Clients will connect to this socket.
        let socket_name = listening_socket.socket_name().to_os_string();

        let loop_handle = event_loop.handle();

        loop_handle
            .insert_source(listening_socket, move |client_stream, _, state| {
                // Inside the callback, you should insert the client into the display.
                //
                // You may also associate some data with the client when inserting the client.
                state
                    .display_handle
                    .insert_client(client_stream, Arc::new(ClientState::default()))
                    .unwrap();
            })
            .expect("Failed to init the wayland event source.");

        // You also need to add the display itself to the event loop, so that client events will be processed by wayland-server.
        loop_handle
            .insert_source(
                Generic::new(display, Interest::READ, Mode::Level),
                |_, display, state| {
                    // Safety: we don't drop the display
                    unsafe {
                        display.get_mut().dispatch_clients(state).unwrap();
                    }
                    Ok(PostAction::Continue)
                },
            )
            .unwrap();

        socket_name
    }

    pub fn surface_under(
        &self,
        _window_id: AutoWindowId,
        pos: Point<f64, Logical>,
    ) -> Option<(WlSurface, Point<f64, Logical>)> {
        self.space
            .element_under(pos)
            .and_then(|(window, location)| {
                window
                    .surface_under(pos - location.to_f64(), WindowSurfaceType::ALL)
                    .map(|(s, p)| (s, (p + location).to_f64()))
            })
    }

    pub fn set_host_size(&mut self, size: Size<i32, Physical>) {
        self.host_size = size;
    }

    pub fn resize_virtual_output(&mut self, size: Size<i32, Logical>) {
        if size.w <= 0 || size.h <= 0 || size == self.virtual_size {
            return;
        }

        self.virtual_size = size;
        self.clear_command_queue();

        if let Some(primary_window) = self
            .windows
            .get(self.default_window_id)
            .and_then(|window| window.primary_window())
        {
            self.configure_primary(primary_window);
            let toplevel = primary_window.toplevel().unwrap();
            if toplevel.is_initial_configure_sent() {
                toplevel.send_pending_configure();
            }
        }

        let overlays = self.overlay_windows(self.default_window_id);
        for overlay in overlays {
            self.center_overlay(&overlay);
        }
    }

    pub fn clear_command_queue(&mut self) {
        self.control_queue.clear();
        self.next_control_action_at = None;
    }

    pub fn presentation_viewport(&self) -> Rectangle<i32, Physical> {
        let host_size = self.host_size;
        if host_size.w <= 0 || host_size.h <= 0 {
            return Rectangle::from_size((0, 0).into());
        }

        let scale_x = host_size.w as f64 / self.virtual_size.w as f64;
        let scale_y = host_size.h as f64 / self.virtual_size.h as f64;
        let scale = scale_x.min(scale_y);

        let width = (self.virtual_size.w as f64 * scale).round() as i32;
        let height = (self.virtual_size.h as f64 * scale).round() as i32;
        let x = (host_size.w - width) / 2;
        let y = (host_size.h - height) / 2;

        Rectangle::new((x, y).into(), (width, height).into())
    }

    pub fn host_to_virtual(&self, pos: Point<f64, Physical>) -> Option<Point<f64, Logical>> {
        let viewport = self.presentation_viewport();
        if viewport.size.w <= 0 || viewport.size.h <= 0 {
            return None;
        }

        let x = pos.x - viewport.loc.x as f64;
        let y = pos.y - viewport.loc.y as f64;
        if x < 0.0 || y < 0.0 || x >= viewport.size.w as f64 || y >= viewport.size.h as f64 {
            return None;
        }

        let scale_x = viewport.size.w as f64 / self.virtual_size.w as f64;
        let scale_y = viewport.size.h as f64 / self.virtual_size.h as f64;
        Some(Point::from((x / scale_x, y / scale_y)))
    }

    pub fn map_new_toplevel(&mut self, window: Window) {
        let window_id = self.default_window_id;
        if !self
            .windows
            .get(window_id)
            .expect("default AutoWC window is missing")
            .has_primary_window()
        {
            self.configure_primary(&window);
            self.space.map_element(window.clone(), (0, 0), false);
            self.windows
                .get_mut(window_id)
                .expect("default AutoWC window is missing")
                .set_primary_window(window.clone());
            self.focus_window(window_id, Some(&window));
            return;
        }

        self.configure_overlay(&window);
        self.space.map_element(window.clone(), (0, 0), false);
        self.windows
            .get_mut(window_id)
            .expect("default AutoWC window is missing")
            .push_overlay_window(window.clone());
        self.focus_window(window_id, Some(&window));
    }

    pub fn remove_toplevel(&mut self, surface: &WlSurface) {
        let window_id = self.default_window_id;
        let primary_matches = self
            .windows
            .get(window_id)
            .and_then(|window| window.primary_window())
            .is_some_and(|window| window.toplevel().unwrap().wl_surface() == surface);

        if primary_matches {
            if let Some(window) = self
                .windows
                .get_mut(window_id)
                .expect("default AutoWC window is missing")
                .take_primary_window()
            {
                self.space.unmap_elem(&window);
            }
            self.promote_overlay(window_id);
            self.maybe_exit_when_empty();
            return;
        }

        if let Some(window) = self
            .windows
            .get_mut(window_id)
            .expect("default AutoWC window is missing")
            .remove_overlay_by_surface(surface)
        {
            self.space.unmap_elem(&window);
            let next_focus = self
                .windows
                .get(window_id)
                .expect("default AutoWC window is missing")
                .next_focus_window();
            self.focus_window(window_id, next_focus.as_ref());
        }

        self.maybe_exit_when_empty();
    }

    pub fn check_child_exit(&mut self) {
        let Some(child) = self.child.as_mut() else {
            return;
        };

        match child.try_wait() {
            Ok(Some(status)) => {
                eprintln!("AutoWC child exited with {status}");
                self.child = None;
                self.maybe_exit_when_empty();
            }
            Ok(None) => {}
            Err(err) => {
                eprintln!("AutoWC failed to poll child process: {err}");
                self.child = None;
                self.maybe_exit_when_empty();
            }
        }
    }

    pub fn handle_toplevel_commit(&mut self, surface: &WlSurface) {
        if let Some(window) = self
            .windows
            .get(self.default_window_id)
            .and_then(|auto_window| auto_window.find_overlay_by_surface(surface))
            .cloned()
        {
            self.center_overlay(&window);
        }
    }

    pub fn configure_primary(&self, window: &Window) {
        let toplevel = window.toplevel().unwrap();
        toplevel.with_pending_state(|state| {
            state.states.unset(xdg_toplevel::State::Fullscreen);
            state.states.set(xdg_toplevel::State::TiledLeft);
            state.states.set(xdg_toplevel::State::TiledRight);
            state.states.set(xdg_toplevel::State::TiledTop);
            state.states.set(xdg_toplevel::State::TiledBottom);
            state.size = Some(self.virtual_size);
        });
    }

    pub fn configure_overlay(&self, window: &Window) {
        let toplevel = window.toplevel().unwrap();
        toplevel.with_pending_state(|state| {
            state.states.unset(xdg_toplevel::State::Fullscreen);
            state.states.unset(xdg_toplevel::State::TiledLeft);
            state.states.unset(xdg_toplevel::State::TiledRight);
            state.states.unset(xdg_toplevel::State::TiledTop);
            state.states.unset(xdg_toplevel::State::TiledBottom);
            state.size = None;
        });
    }

    pub fn focus_window(&mut self, window_id: AutoWindowId, window: Option<&Window>) {
        let surface = window.map(|window| window.toplevel().unwrap().wl_surface().clone());
        let serial = SERIAL_COUNTER.next_serial();

        if let Some(window) = window {
            self.space.raise_element(window, true);
        }

        for window in self.mapped_windows(window_id) {
            let toplevel = window.toplevel().unwrap();
            let activated = surface
                .as_ref()
                .is_some_and(|surface| toplevel.wl_surface() == surface);
            if window.set_activated(activated) && toplevel.is_initial_configure_sent() {
                toplevel.send_pending_configure();
            }
        }

        let keyboard = self.seat.get_keyboard().unwrap();
        keyboard.set_focus(self, surface, serial);
    }

    pub fn queue_screenshot(&mut self, window_id: AutoWindowId, path: Option<PathBuf>) {
        let path = match path {
            Some(path) => path,
            None => {
                let path = self.next_screenshot_path();
                self.autogenerated_screenshots.push(path.clone());
                path
            }
        };
        self.pending_screenshots
            .push_back(ScreenshotRequest { window_id, path });
    }

    pub fn request_shutdown(&mut self) {
        self.cleanup_autogenerated_screenshots();
        self.loop_signal.stop();
    }

    fn cleanup_autogenerated_screenshots(&mut self) {
        cleanup_screenshot_paths(self.autogenerated_screenshots.drain(..));
    }

    fn next_screenshot_path(&mut self) -> PathBuf {
        let pid = std::process::id();

        loop {
            self.screenshot_counter += 1;
            let path = std::env::temp_dir().join(format!(
                "autowc-screenshot-{pid}-{}.png",
                self.screenshot_counter
            ));
            if !path.exists() {
                return path;
            }
        }
    }

    fn promote_overlay(&mut self, window_id: AutoWindowId) {
        let Some(window) = self
            .windows
            .get_mut(window_id)
            .expect("default AutoWC window is missing")
            .promote_last_overlay()
        else {
            self.focus_window(window_id, None);
            return;
        };

        self.configure_primary(&window);
        self.space.map_element(window.clone(), (0, 0), false);
        self.focus_window(window_id, Some(&window));

        let overlays = self.overlay_windows(window_id);
        for overlay in overlays {
            self.center_overlay(&overlay);
        }
    }

    pub fn mapped_windows(&self, window_id: AutoWindowId) -> Vec<Window> {
        self.windows
            .get(window_id)
            .map(|window| window.mapped_windows())
            .unwrap_or_default()
    }

    fn overlay_windows(&self, window_id: AutoWindowId) -> Vec<Window> {
        self.windows
            .get(window_id)
            .map(|window| window.overlay_windows().cloned().collect())
            .unwrap_or_default()
    }

    fn maybe_exit_when_empty(&mut self) {
        if !self.stay_alive && self.windows.is_empty() {
            self.request_shutdown();
        }
    }

    fn center_overlay(&mut self, window: &Window) {
        let geometry = window.geometry();
        if geometry.size.w <= 0 || geometry.size.h <= 0 {
            return;
        }

        // TODO: Replace this with a real overlay policy. This should eventually
        // consider xdg parent/transient relationships and clamp to the output.
        let x = ((self.virtual_size.w - geometry.size.w) / 2).max(0);
        let y = ((self.virtual_size.h - geometry.size.h) / 2).max(0);
        self.space.map_element(window.clone(), (x, y), false);
    }
}

fn cleanup_screenshot_paths(paths: impl IntoIterator<Item = PathBuf>) {
    for path in paths {
        match std::fs::remove_file(&path) {
            Ok(()) => {}
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(err) => eprintln!(
                "AutoWC failed to remove autogenerated screenshot {}: {err}",
                path.display()
            ),
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct TimingOptions {
    pub key_event_interval: Duration,
    pub chord_key_interval: Duration,
    pub chord_hold_duration: Duration,
    pub command_interval: Duration,
}

impl Default for TimingOptions {
    fn default() -> Self {
        Self {
            key_event_interval: crate::input::DEFAULT_KEY_EVENT_INTERVAL,
            chord_key_interval: crate::input::DEFAULT_CHORD_KEY_INTERVAL,
            chord_hold_duration: crate::input::DEFAULT_CHORD_HOLD_DURATION,
            command_interval: crate::input::DEFAULT_COMMAND_INTERVAL,
        }
    }
}

/// Data associated with a wayland client that connects to AutoWC.
/// One instance of this type per client.
#[derive(Default)]
pub struct ClientState {
    pub compositor_state: CompositorClientState,
}

pub struct ScreenshotRequest {
    pub window_id: AutoWindowId,
    pub path: PathBuf,
}

pub struct QueuedControlAction {
    pub window_id: AutoWindowId,
    pub kind: QueuedControlActionKind,
}

pub enum QueuedControlActionKind {
    Key { code: u32, state: KeyState },
    PointerMove { x: f64, y: f64 },
    PointerButton { button: u32, state: ButtonState },
    Scroll { dx: f64, dy: f64 },
    Screenshot { path: Option<PathBuf> },
    Quit,
    Delay(Duration),
}

impl ClientData for ClientState {
    fn initialized(&self, _client_id: ClientId) {}
    fn disconnected(&self, _client_id: ClientId, _reason: DisconnectReason) {}
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cleanup_screenshot_paths_removes_existing_files_and_ignores_missing_files() {
        let pid = std::process::id();
        let path = std::env::temp_dir().join(format!("autowc-cleanup-test-{pid}.png"));
        let missing_path = std::env::temp_dir().join(format!("autowc-cleanup-missing-{pid}.png"));

        std::fs::write(&path, b"test").unwrap();
        let _ = std::fs::remove_file(&missing_path);

        cleanup_screenshot_paths([path.clone(), missing_path]);

        assert!(!path.exists());
    }
}
