use std::{
    collections::VecDeque,
    ffi::OsString,
    path::PathBuf,
    process::Child,
    sync::Arc,
    time::{Duration, Instant},
};

use smithay::{
    backend::input::{ButtonState, KeyState},
    desktop::{PopupManager, Space, Window, WindowSurfaceType},
    input::{Seat, SeatState},
    output::Output,
    reexports::{
        calloop::{generic::Generic, EventLoop, Interest, LoopSignal, Mode, PostAction},
        wayland_protocols::xdg::shell::server::xdg_toplevel,
        wayland_server::{
            backend::{ClientData, ClientId, DisconnectReason},
            protocol::wl_surface::WlSurface,
            Display, DisplayHandle,
        },
        winit::window::WindowId as HostWindowId,
    },
    utils::{Logical, Physical, Point, Rectangle, Size, SERIAL_COUNTER},
    wayland::{
        compositor::{CompositorClientState, CompositorState},
        output::OutputManagerState,
        selection::data_device::DataDeviceState,
        shell::xdg::XdgShellState,
        shm::ShmState,
        socket::ListeningSocketSource,
    },
};

use crate::{
    host_winit::HostWindowRequester,
    protocol::Protocol,
    window::{AutoWindowId, AutoWindowState, WindowRegistry},
};

pub struct AutoWC {
    pub start_time: std::time::Instant,
    pub socket_name: OsString,
    pub display_handle: DisplayHandle,

    pub loop_signal: LoopSignal,
    pub initial_virtual_size: Size<i32, Logical>,
    pub dynamic_resize: bool,
    pub windows: WindowRegistry,
    pub first_alive_window_id: Option<AutoWindowId>,
    pub focused_window_id: Option<AutoWindowId>,
    pub host_window_requester: Option<HostWindowRequester>,
    pub child: Option<Child>,
    pub stay_alive: bool,
    pub pending_screenshots: VecDeque<ScreenshotRequest>,
    pub control_queue: VecDeque<QueuedControlAction>,
    pub next_control_action_at: Option<Instant>,
    pub key_event_interval: Duration,
    pub chord_key_interval: Duration,
    pub chord_hold_duration: Duration,
    pub command_interval: Duration,
    pub protocol: Protocol,
    screenshot_counter: u64,
    autogenerated_screenshots: Vec<PathBuf>,

    // Smithay State
    pub compositor_state: CompositorState,
    pub xdg_shell_state: XdgShellState,
    pub shm_state: ShmState,
    pub output_manager_state: OutputManagerState,
    pub seat_state: SeatState<AutoWC>,
    pub data_device_state: DataDeviceState,
    pub popups: PopupManager,

    pub seat: Seat<Self>,
}

impl AutoWC {
    pub fn new(
        event_loop: &mut EventLoop<Self>,
        display: Display<Self>,
        initial_virtual_size: Size<i32, Logical>,
        dynamic_resize: bool,
        stay_alive: bool,
        timing: TimingOptions,
        protocol: Protocol,
    ) -> Self {
        let start_time = std::time::Instant::now();

        let dh = display.handle();

        // Here we initialize implementations of some wayland protocols
        // Some of them require us to implement traits on the AutoWC state,
        // you can find those implementations in the `crate::handlers` module

        // Initialize protocols needed for displaying windows
        let compositor_state = CompositorState::new::<Self>(&dh);
        let xdg_shell_state = XdgShellState::new::<Self>(&dh);
        let shm_state = ShmState::new::<Self>(&dh, vec![]);
        let popups = PopupManager::default();

        let output_manager_state = OutputManagerState::new_with_xdg_output::<Self>(&dh);

        // Data device is responsible for clipboard and drag-and-drop
        let data_device_state = DataDeviceState::new::<Self>(&dh);

        // A seat is a group of keyboards, pointer and touch devices.
        // A seat typically has a pointer and maintains a keyboard focus and a pointer focus.
        let mut seat_state = SeatState::new();
        let mut seat: Seat<Self> = seat_state.new_wl_seat(&dh, "winit");

        // Notify clients that we have a keyboard, for the sake of the example we assume that keyboard is always present.
        // You may want to track keyboard hot-plug in real compositor.
        seat.add_keyboard(Default::default(), 200, 25).unwrap();

        // Notify clients that we have a pointer (mouse)
        // Here we assume that there is always pointer plugged in
        seat.add_pointer();

        // Setup a wayland socket that will be used to accept clients
        let socket_name = Self::init_wayland_listener(display, event_loop);

        // Get the loop signal, used to stop the event loop
        let loop_signal = event_loop.get_signal();

        Self {
            start_time,
            display_handle: dh,

            loop_signal,
            socket_name,
            initial_virtual_size,
            dynamic_resize,
            windows: WindowRegistry::new(),
            first_alive_window_id: None,
            focused_window_id: None,
            host_window_requester: None,
            child: None,
            stay_alive,
            pending_screenshots: VecDeque::new(),
            control_queue: VecDeque::new(),
            next_control_action_at: None,
            key_event_interval: timing.key_event_interval,
            chord_key_interval: timing.chord_key_interval,
            chord_hold_duration: timing.chord_hold_duration,
            command_interval: timing.command_interval,
            protocol,
            screenshot_counter: 0,
            autogenerated_screenshots: Vec::new(),

            compositor_state,
            xdg_shell_state,
            shm_state,
            output_manager_state,
            seat_state,
            data_device_state,
            popups,
            seat,
        }
    }

    fn init_wayland_listener(
        display: Display<AutoWC>,
        event_loop: &mut EventLoop<Self>,
    ) -> OsString {
        // Creates a new listening socket, automatically choosing the next available `wayland` socket name.
        let listening_socket = ListeningSocketSource::new_auto().unwrap();

        // Get the name of the listening socket.
        // Clients will connect to this socket.
        let socket_name = listening_socket.socket_name().to_os_string();

        let loop_handle = event_loop.handle();

        loop_handle
            .insert_source(listening_socket, move |client_stream, _, state| {
                // Inside the callback, you should insert the client into the display.
                //
                // You may also associate some data with the client when inserting the client.
                state
                    .display_handle
                    .insert_client(client_stream, Arc::new(ClientState::default()))
                    .unwrap();
            })
            .expect("Failed to init the wayland event source.");

        // You also need to add the display itself to the event loop, so that client events will be processed by wayland-server.
        loop_handle
            .insert_source(
                Generic::new(display, Interest::READ, Mode::Level),
                |_, display, state| {
                    // Safety: we don't drop the display
                    unsafe {
                        display.get_mut().dispatch_clients(state).unwrap();
                    }
                    let _ = state.display_handle.flush_clients();
                    Ok(PostAction::Continue)
                },
            )
            .unwrap();

        socket_name
    }

    pub fn surface_under(
        &self,
        window_id: AutoWindowId,
        pos: Point<f64, Logical>,
    ) -> Option<(WlSurface, Point<f64, Logical>)> {
        self.windows
            .get(window_id)?
            .space()
            .element_under(pos)
            .and_then(|(window, location)| {
                window
                    .surface_under(pos - location.to_f64(), WindowSurfaceType::ALL)
                    .map(|(s, p)| (s, (p + location).to_f64()))
            })
    }

    pub fn element_under(
        &self,
        window_id: AutoWindowId,
        pos: Point<f64, Logical>,
    ) -> Option<Window> {
        self.windows
            .get(window_id)?
            .space()
            .element_under(pos)
            .map(|(window, _)| window.clone())
    }

    pub fn window_space(&self, window_id: AutoWindowId) -> Option<&Space<Window>> {
        self.windows.get(window_id).map(|window| window.space())
    }

    pub fn map_output_for_window(&mut self, window_id: AutoWindowId, output: &Output) {
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .space_mut()
            .map_output(output, (0, 0));
    }

    pub fn output_geometry_for_window(
        &self,
        window_id: AutoWindowId,
        output: &Output,
    ) -> Option<Rectangle<i32, Logical>> {
        self.windows.get(window_id)?.space().output_geometry(output)
    }

    pub fn element_geometry_for_window(
        &self,
        window_id: AutoWindowId,
        window: &Window,
    ) -> Option<Rectangle<i32, Logical>> {
        self.windows
            .get(window_id)?
            .space()
            .element_geometry(window)
    }

    pub fn refresh_window_space(&mut self, window_id: AutoWindowId) {
        if let Some(window) = self.windows.get_mut(window_id) {
            window.space_mut().refresh();
        }
    }

    pub fn set_host_window_requester(&mut self, requester: HostWindowRequester) {
        self.host_window_requester = Some(requester);
    }

    pub fn clear_command_queue(&mut self) {
        self.control_queue.clear();
        self.next_control_action_at = None;
    }

    pub fn presentation_viewport(&self, window_id: AutoWindowId) -> Rectangle<i32, Physical> {
        let host_size = self.window_host_size(window_id);
        if host_size.w <= 0 || host_size.h <= 0 {
            return Rectangle::from_size((0, 0).into());
        }

        let virtual_size = self.window_virtual_size(window_id);
        let scale_x = host_size.w as f64 / virtual_size.w as f64;
        let scale_y = host_size.h as f64 / virtual_size.h as f64;
        let scale = scale_x.min(scale_y);

        let width = (virtual_size.w as f64 * scale).round() as i32;
        let height = (virtual_size.h as f64 * scale).round() as i32;
        let x = (host_size.w - width) / 2;
        let y = (host_size.h - height) / 2;

        Rectangle::new((x, y).into(), (width, height).into())
    }

    pub fn host_to_virtual(
        &self,
        window_id: AutoWindowId,
        pos: Point<f64, Physical>,
    ) -> Option<Point<f64, Logical>> {
        let viewport = self.presentation_viewport(window_id);
        if viewport.size.w <= 0 || viewport.size.h <= 0 {
            return None;
        }

        let x = pos.x - viewport.loc.x as f64;
        let y = pos.y - viewport.loc.y as f64;
        if x < 0.0 || y < 0.0 || x >= viewport.size.w as f64 || y >= viewport.size.h as f64 {
            return None;
        }

        let virtual_size = self.window_virtual_size(window_id);
        let scale_x = viewport.size.w as f64 / virtual_size.w as f64;
        let scale_y = viewport.size.h as f64 / virtual_size.h as f64;
        Some(Point::from((x / scale_x, y / scale_y)))
    }

    pub fn map_new_toplevel(&mut self, window: Window) {
        let window_id = self.windows.create_window();

        self.configure_probe(&window);
        window.toplevel().unwrap().send_configure();
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .set_primary_window(window.clone());
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .set_state(AutoWindowState::WaitingProbeCommit);
        self.note_window_alive(window_id);
    }

    pub fn handle_toplevel_commit(&mut self, surface: &WlSurface) {
        let Some(window_id) = self.windows.find_id_by_surface(surface) else {
            return;
        };
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|auto_window| auto_window.primary_window())
            .cloned()
        else {
            return;
        };

        match self
            .windows
            .get(window_id)
            .expect("AutoWC window is missing")
            .state()
        {
            AutoWindowState::WaitingProbeCommit => {
                let preferred_size = self.preferred_toplevel_size(&window);
                if let Some(requester) = &self.host_window_requester {
                    requester.create_window(window_id, preferred_size);
                    self.windows
                        .get_mut(window_id)
                        .expect("AutoWC window is missing")
                        .set_state(AutoWindowState::WaitingHostWindow);
                } else {
                    eprintln!("AutoWC cannot create host window: winit backend is not initialized");
                }
            }
            AutoWindowState::WaitingFinalCommit => {
                self.map_configured_window(window_id);
            }
            AutoWindowState::Mapped => {
                if self
                    .windows
                    .get(window_id)
                    .expect("AutoWC window is missing")
                    .find_overlay_by_surface(surface)
                    .is_some()
                {
                    self.center_overlay(window_id, &window);
                }
            }
            AutoWindowState::Empty | AutoWindowState::WaitingHostWindow => {}
        }
    }

    pub fn bind_host_window(
        &mut self,
        window_id: AutoWindowId,
        host_window_id: HostWindowId,
        output: Output,
        host_size: Size<i32, Physical>,
        virtual_size: Size<i32, Logical>,
    ) {
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|auto_window| auto_window.primary_window())
            .cloned()
        else {
            return;
        };

        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .set_host_window(host_window_id, output, host_size, virtual_size);

        if self.preferred_toplevel_size(&window) == virtual_size {
            self.configure_toplevel(&window, virtual_size);
            window.toplevel().unwrap().send_pending_configure();
            self.map_configured_window(window_id);
        } else {
            self.configure_toplevel(&window, virtual_size);
            window.toplevel().unwrap().send_pending_configure();
            self.windows
                .get_mut(window_id)
                .expect("AutoWC window is missing")
                .set_state(AutoWindowState::WaitingFinalCommit);
        }
    }

    pub fn resize_window_host(
        &mut self,
        window_id: AutoWindowId,
        host_size: Size<i32, Physical>,
        virtual_size: Size<i32, Logical>,
    ) {
        if host_size.w <= 0 || host_size.h <= 0 || virtual_size.w <= 0 || virtual_size.h <= 0 {
            return;
        }
        let auto_window = self
            .windows
            .get_mut(window_id)
            .expect("AutoWC window is missing");
        auto_window.set_host_size(host_size);
        auto_window.set_virtual_size(virtual_size);
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|auto_window| auto_window.primary_window())
            .cloned()
        else {
            return;
        };
        self.configure_toplevel(&window, virtual_size);
        let toplevel = window.toplevel().unwrap();
        if toplevel.is_initial_configure_sent() {
            toplevel.send_pending_configure();
        }
    }

    pub fn remove_toplevel(&mut self, surface: &WlSurface) {
        let Some(window_id) = self.windows.find_id_by_surface(surface) else {
            self.maybe_exit_when_empty();
            return;
        };
        let primary_matches = self
            .windows
            .get(window_id)
            .and_then(|window| window.primary_window())
            .is_some_and(|window| window.toplevel().unwrap().wl_surface() == surface);

        if primary_matches {
            if let Some(window) = self
                .windows
                .get_mut(window_id)
                .expect("AutoWC window is missing")
                .take_primary_window()
            {
                self.windows
                    .get_mut(window_id)
                    .expect("AutoWC window is missing")
                    .space_mut()
                    .unmap_elem(&window);
            }
            if let Some(host_window_id) = self
                .windows
                .get(window_id)
                .and_then(|window| window.host_window_id())
            {
                if let Some(requester) = &self.host_window_requester {
                    requester.close_window(host_window_id);
                }
            }
            self.promote_overlay(window_id);
            self.refresh_first_alive_window();
            self.maybe_exit_when_empty();
            return;
        }

        if let Some(window) = self
            .windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .remove_overlay_by_surface(surface)
        {
            self.windows
                .get_mut(window_id)
                .expect("AutoWC window is missing")
                .space_mut()
                .unmap_elem(&window);
            let next_focus = self
                .windows
                .get(window_id)
                .expect("AutoWC window is missing")
                .next_focus_window();
            self.focus_window(window_id, next_focus.as_ref());
        }

        self.refresh_first_alive_window();
        self.maybe_exit_when_empty();
    }

    pub fn check_child_exit(&mut self) {
        let Some(child) = self.child.as_mut() else {
            return;
        };

        match child.try_wait() {
            Ok(Some(status)) => {
                eprintln!("AutoWC child exited with {status}");
                self.child = None;
                self.maybe_exit_when_empty();
            }
            Ok(None) => {}
            Err(err) => {
                eprintln!("AutoWC failed to poll child process: {err}");
                self.child = None;
                self.maybe_exit_when_empty();
            }
        }
    }

    pub fn configure_probe(&self, window: &Window) {
        let toplevel = window.toplevel().unwrap();
        toplevel.with_pending_state(|state| {
            state.states.unset(xdg_toplevel::State::Fullscreen);
            state.states.unset(xdg_toplevel::State::TiledLeft);
            state.states.unset(xdg_toplevel::State::TiledRight);
            state.states.unset(xdg_toplevel::State::TiledTop);
            state.states.unset(xdg_toplevel::State::TiledBottom);
            state.size = None;
        });
    }

    pub fn configure_toplevel(&self, window: &Window, size: Size<i32, Logical>) {
        let toplevel = window.toplevel().unwrap();
        toplevel.with_pending_state(|state| {
            state.states.unset(xdg_toplevel::State::Fullscreen);
            state.states.set(xdg_toplevel::State::TiledLeft);
            state.states.set(xdg_toplevel::State::TiledRight);
            state.states.set(xdg_toplevel::State::TiledTop);
            state.states.set(xdg_toplevel::State::TiledBottom);
            state.size = Some(size);
        });
    }

    pub fn focus_window(&mut self, window_id: AutoWindowId, window: Option<&Window>) {
        let surface = window.map(|window| window.toplevel().unwrap().wl_surface().clone());
        let serial = SERIAL_COUNTER.next_serial();

        if let Some(window) = window {
            self.windows
                .get_mut(window_id)
                .expect("AutoWC window is missing")
                .space_mut()
                .raise_element(window, true);
        }

        for window in self.mapped_windows() {
            let toplevel = window.toplevel().unwrap();
            let activated = surface
                .as_ref()
                .is_some_and(|surface| toplevel.wl_surface() == surface);
            if window.set_activated(activated) && toplevel.is_initial_configure_sent() {
                toplevel.send_pending_configure();
            }
        }

        self.focused_window_id = surface.as_ref().map(|_| window_id);
        let keyboard = self.seat.get_keyboard().unwrap();
        keyboard.set_focus(self, surface, serial);
    }

    pub fn focus_auto_window(&mut self, window_id: AutoWindowId) {
        let window = self
            .windows
            .get(window_id)
            .and_then(|window| window.next_focus_window());
        self.focus_window(window_id, window.as_ref());
    }

    pub fn blur_auto_window(&mut self, window_id: AutoWindowId) {
        if self.focused_window_id == Some(window_id) {
            self.focus_window(window_id, None);
        }
    }

    pub fn queue_screenshot(&mut self, window_id: AutoWindowId, path: Option<PathBuf>) {
        let path = match path {
            Some(path) => path,
            None => {
                let path = self.next_screenshot_path();
                self.autogenerated_screenshots.push(path.clone());
                path
            }
        };
        self.pending_screenshots
            .push_back(ScreenshotRequest { window_id, path });
    }

    pub fn request_shutdown(&mut self) {
        self.cleanup_autogenerated_screenshots();
        self.loop_signal.stop();
    }

    fn cleanup_autogenerated_screenshots(&mut self) {
        cleanup_screenshot_paths(self.autogenerated_screenshots.drain(..));
    }

    fn next_screenshot_path(&mut self) -> PathBuf {
        let pid = std::process::id();

        loop {
            self.screenshot_counter += 1;
            let path = std::env::temp_dir().join(format!(
                "autowc-screenshot-{pid}-{}.png",
                self.screenshot_counter
            ));
            if !path.exists() {
                return path;
            }
        }
    }

    fn promote_overlay(&mut self, window_id: AutoWindowId) {
        let Some(window) = self
            .windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .promote_last_overlay()
        else {
            self.focus_window(window_id, None);
            return;
        };

        let virtual_size = self.window_virtual_size(window_id);
        self.configure_toplevel(&window, virtual_size);
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .space_mut()
            .map_element(window.clone(), (0, 0), false);
        self.focus_window(window_id, Some(&window));

        let overlays = self.overlay_windows(window_id);
        for overlay in overlays {
            self.center_overlay(window_id, &overlay);
        }
    }

    pub fn mapped_windows_for(&self, window_id: AutoWindowId) -> Vec<Window> {
        self.windows
            .get(window_id)
            .map(|window| window.mapped_windows())
            .unwrap_or_default()
    }

    pub fn mapped_windows(&self) -> Vec<Window> {
        self.windows.mapped_windows()
    }

    fn overlay_windows(&self, window_id: AutoWindowId) -> Vec<Window> {
        self.windows
            .get(window_id)
            .map(|window| window.overlay_windows().cloned().collect())
            .unwrap_or_default()
    }

    fn maybe_exit_when_empty(&mut self) {
        if !self.stay_alive && self.windows.is_empty() {
            self.request_shutdown();
        }
    }

    fn note_window_alive(&mut self, window_id: AutoWindowId) {
        self.first_alive_window_id = Some(match self.first_alive_window_id {
            Some(first_alive_window_id) if first_alive_window_id.raw() < window_id.raw() => {
                first_alive_window_id
            }
            _ => window_id,
        });
    }

    fn refresh_first_alive_window(&mut self) {
        self.first_alive_window_id = self.windows.first_alive_id();
    }

    pub fn output_for_window(&self, window_id: AutoWindowId) -> Option<Output> {
        self.windows
            .get(window_id)
            .and_then(|window| window.output().cloned())
    }

    pub fn window_virtual_size(&self, window_id: AutoWindowId) -> Size<i32, Logical> {
        self.windows
            .get(window_id)
            .and_then(|window| window.virtual_size())
            .unwrap_or(self.initial_virtual_size)
    }

    fn window_host_size(&self, window_id: AutoWindowId) -> Size<i32, Physical> {
        self.windows
            .get(window_id)
            .and_then(|window| window.host_size())
            .unwrap_or_else(|| self.initial_virtual_size.to_physical(1))
    }

    pub fn find_window_by_host_window(&self, host_window_id: HostWindowId) -> Option<AutoWindowId> {
        self.windows.find_id_by_host_window(host_window_id)
    }

    pub fn close_host_window(&mut self, host_window_id: HostWindowId) {
        let Some(window_id) = self.find_window_by_host_window(host_window_id) else {
            return;
        };
        if let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|window| window.primary_window())
        {
            window.toplevel().unwrap().send_close();
        }
    }

    fn map_configured_window(&mut self, window_id: AutoWindowId) {
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|auto_window| auto_window.primary_window())
            .cloned()
        else {
            return;
        };
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .space_mut()
            .map_element(window.clone(), (0, 0), false);
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .set_state(AutoWindowState::Mapped);
        self.focus_window(window_id, Some(&window));
    }

    fn preferred_toplevel_size(&self, window: &Window) -> Size<i32, Logical> {
        let size = window.geometry().size;
        if size.w > 0 && size.h > 0 {
            size
        } else {
            self.initial_virtual_size
        }
    }

    fn center_overlay(&mut self, window_id: AutoWindowId, window: &Window) {
        let geometry = window.geometry();
        if geometry.size.w <= 0 || geometry.size.h <= 0 {
            return;
        }

        let virtual_size = self.window_virtual_size(window_id);
        // TODO: Replace this with a real overlay policy. This should eventually
        // consider xdg parent/transient relationships and clamp to the output.
        let x = ((virtual_size.w - geometry.size.w) / 2).max(0);
        let y = ((virtual_size.h - geometry.size.h) / 2).max(0);
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .space_mut()
            .map_element(window.clone(), (x, y), false);
    }
}

fn cleanup_screenshot_paths(paths: impl IntoIterator<Item = PathBuf>) {
    for path in paths {
        match std::fs::remove_file(&path) {
            Ok(()) => {}
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(err) => eprintln!(
                "AutoWC failed to remove autogenerated screenshot {}: {err}",
                path.display()
            ),
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct TimingOptions {
    pub key_event_interval: Duration,
    pub chord_key_interval: Duration,
    pub chord_hold_duration: Duration,
    pub command_interval: Duration,
}

impl Default for TimingOptions {
    fn default() -> Self {
        Self {
            key_event_interval: crate::input::DEFAULT_KEY_EVENT_INTERVAL,
            chord_key_interval: crate::input::DEFAULT_CHORD_KEY_INTERVAL,
            chord_hold_duration: crate::input::DEFAULT_CHORD_HOLD_DURATION,
            command_interval: crate::input::DEFAULT_COMMAND_INTERVAL,
        }
    }
}

/// Data associated with a wayland client that connects to AutoWC.
/// One instance of this type per client.
#[derive(Default)]
pub struct ClientState {
    pub compositor_state: CompositorClientState,
}

pub struct ScreenshotRequest {
    pub window_id: AutoWindowId,
    pub path: PathBuf,
}

pub struct QueuedControlAction {
    pub window_id: AutoWindowId,
    pub kind: QueuedControlActionKind,
}

pub enum QueuedControlActionKind {
    Key { code: u32, state: KeyState },
    PointerMove { x: f64, y: f64 },
    PointerButton { button: u32, state: ButtonState },
    Scroll { dx: f64, dy: f64 },
    Screenshot { path: Option<PathBuf> },
    Quit,
    Delay(Duration),
}

impl ClientData for ClientState {
    fn initialized(&self, _client_id: ClientId) {}
    fn disconnected(&self, _client_id: ClientId, _reason: DisconnectReason) {}
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cleanup_screenshot_paths_removes_existing_files_and_ignores_missing_files() {
        let pid = std::process::id();
        let path = std::env::temp_dir().join(format!("autowc-cleanup-test-{pid}.png"));
        let missing_path = std::env::temp_dir().join(format!("autowc-cleanup-missing-{pid}.png"));

        std::fs::write(&path, b"test").unwrap();
        let _ = std::fs::remove_file(&missing_path);

        cleanup_screenshot_paths([path.clone(), missing_path]);

        assert!(!path.exists());
    }
}
