use std::{
    collections::{HashMap, HashSet, VecDeque},
    ffi::OsString,
    path::PathBuf,
    process::{Child, Command, Stdio},
    sync::Arc,
    thread::JoinHandle,
    time::{Duration, Instant},
};

use smithay::{
    backend::input::{ButtonState, KeyState, Keycode},
    desktop::{PopupManager, Space, Window, WindowSurfaceType},
    input::{Seat, SeatState},
    output::Output,
    reexports::{
        calloop::{generic::Generic, EventLoop, Interest, LoopSignal, Mode, PostAction},
        wayland_protocols::xdg::shell::server::xdg_toplevel,
        wayland_server::{
            backend::{ClientData, ClientId, DisconnectReason},
            protocol::wl_surface::WlSurface,
            Display, DisplayHandle,
        },
        winit::window::WindowId as HostWindowId,
    },
    utils::{Logical, Physical, Point, Rectangle, Size, SERIAL_COUNTER},
    wayland::{
        compositor::{with_states, CompositorClientState, CompositorState},
        output::OutputManagerState,
        selection::data_device::DataDeviceState,
        shell::xdg::{XdgShellState, XdgToplevelSurfaceData},
        shm::ShmState,
        socket::ListeningSocketSource,
    },
};
use tracing::{debug, error, info, trace, warn};

use crate::{
    host::HostWindowRequester,
    protocol::{ControlResponse, Protocol, WindowInfo},
    window::{AutoWindowId, AutoWindowState, WindowGeometry, WindowRegistry, WindowSizing},
};

mod clipboard;
mod output;

const CHILD_TERMINATION_GRACE_PERIOD: Duration = Duration::from_secs(2);
const CHILD_TERMINATION_POLL_INTERVAL: Duration = Duration::from_millis(50);
const CHILD_KILL_GRACE_PERIOD: Duration = Duration::from_millis(500);

pub struct AutoWC {
    pub start_time: std::time::Instant,
    pub socket_name: OsString,
    pub display_handle: DisplayHandle,

    pub loop_signal: LoopSignal,
    pub initial_virtual_size: Size<i32, Logical>,
    pub windows: WindowRegistry,
    pub first_alive_window_id: Option<AutoWindowId>,
    pub focused_window_id: Option<AutoWindowId>,
    pub host_window_requester: Option<HostWindowRequester>,
    pub launched_children: Vec<Child>,
    pub clipboard_sync_threads: Vec<JoinHandle<()>>,
    pub(crate) pending_clipboard_sync: Option<clipboard::PendingClipboardSync>,
    pub stay_alive: bool,
    pub pending_screenshots: VecDeque<ScreenshotRequest>,
    pub(crate) host_pressed_keys: HashMap<AutoWindowId, HashSet<Keycode>>,
    pub control_queue: VecDeque<QueuedControlAction>,
    pub next_control_action_at: Option<Instant>,
    pub key_event_interval: Duration,
    pub chord_key_interval: Duration,
    pub chord_hold_duration: Duration,
    pub command_interval: Duration,
    pub protocol: Protocol,
    pub control_responses: ControlResponseQueue,
    pub delivered_control_responses: HashSet<ControlResponseHandle>,
    next_output_id: u64,
    pending_output: Output,
    screenshot_counter: u64,
    autogenerated_screenshots: Vec<PathBuf>,

    // Smithay State
    pub compositor_state: CompositorState,
    pub xdg_shell_state: XdgShellState,
    pub shm_state: ShmState,
    pub output_manager_state: OutputManagerState,
    pub seat_state: SeatState<AutoWC>,
    pub data_device_state: DataDeviceState,
    pub popups: PopupManager,

    pub seat: Seat<Self>,
}

impl AutoWC {
    pub fn new(
        event_loop: &mut EventLoop<Self>,
        display: Display<Self>,
        initial_virtual_size: Size<i32, Logical>,
        stay_alive: bool,
        timing: TimingOptions,
        protocol: Protocol,
    ) -> Self {
        let start_time = std::time::Instant::now();
        debug!(
            ?initial_virtual_size,
            stay_alive,
            ?timing,
            ?protocol,
            "initializing compositor state"
        );

        let dh = display.handle();

        // Here we initialize implementations of some wayland protocols
        // Some of them require us to implement traits on the AutoWC state,
        // you can find those implementations in the `crate::wayland` module

        // Initialize protocols needed for displaying windows
        let compositor_state = CompositorState::new::<Self>(&dh);
        let xdg_shell_state = XdgShellState::new::<Self>(&dh);
        let shm_state = ShmState::new::<Self>(&dh, vec![]);
        let popups = PopupManager::default();

        let output_manager_state = OutputManagerState::new_with_xdg_output::<Self>(&dh);

        // Data device is responsible for clipboard and drag-and-drop
        let data_device_state = DataDeviceState::new::<Self>(&dh);

        // A seat is a group of keyboards, pointer and touch devices.
        // A seat typically has a pointer and maintains a keyboard focus and a pointer focus.
        let mut seat_state = SeatState::new();
        let mut seat: Seat<Self> = seat_state.new_wl_seat(&dh, "winit");

        // Notify clients that we have a keyboard, for the sake of the example we assume that keyboard is always present.
        // You may want to track keyboard hot-plug in real compositor.
        seat.add_keyboard(Default::default(), 200, 25).unwrap();

        // Notify clients that we have a pointer (mouse)
        // Here we assume that there is always pointer plugged in
        seat.add_pointer();

        // Setup a wayland socket that will be used to accept clients
        let socket_name = Self::init_wayland_listener(display, event_loop);
        info!(socket = ?socket_name, "listening for nested wayland clients");

        // Get the loop signal, used to stop the event loop
        let loop_signal = event_loop.get_signal();
        let mut next_output_id = 1;
        let pending_output = output::create_output(&dh, initial_virtual_size, &mut next_output_id);

        Self {
            start_time,
            display_handle: dh,

            loop_signal,
            socket_name,
            initial_virtual_size,
            windows: WindowRegistry::new(),
            first_alive_window_id: None,
            focused_window_id: None,
            host_window_requester: None,
            launched_children: Vec::new(),
            clipboard_sync_threads: Vec::new(),
            pending_clipboard_sync: None,
            stay_alive,
            pending_screenshots: VecDeque::new(),
            host_pressed_keys: HashMap::new(),
            control_queue: VecDeque::new(),
            next_control_action_at: None,
            key_event_interval: timing.key_event_interval,
            chord_key_interval: timing.chord_key_interval,
            chord_hold_duration: timing.chord_hold_duration,
            command_interval: timing.command_interval,
            protocol,
            control_responses: ControlResponseQueue::default(),
            delivered_control_responses: HashSet::new(),
            next_output_id,
            pending_output,
            screenshot_counter: 0,
            autogenerated_screenshots: Vec::new(),

            compositor_state,
            xdg_shell_state,
            shm_state,
            output_manager_state,
            seat_state,
            data_device_state,
            popups,
            seat,
        }
    }

    fn init_wayland_listener(
        display: Display<AutoWC>,
        event_loop: &mut EventLoop<Self>,
    ) -> OsString {
        // Creates a new listening socket, automatically choosing the next available `wayland` socket name.
        let listening_socket = ListeningSocketSource::new_auto().unwrap();

        // Get the name of the listening socket.
        // Clients will connect to this socket.
        let socket_name = listening_socket.socket_name().to_os_string();

        let loop_handle = event_loop.handle();

        loop_handle
            .insert_source(listening_socket, move |client_stream, _, state| {
                // Inside the callback, you should insert the client into the display.
                //
                // You may also associate some data with the client when inserting the client.
                debug!("accepting nested wayland client");
                state
                    .display_handle
                    .insert_client(client_stream, Arc::new(ClientState::default()))
                    .unwrap();
            })
            .expect("Failed to init the wayland event source.");

        // You also need to add the display itself to the event loop, so that client events will be processed by wayland-server.
        loop_handle
            .insert_source(
                Generic::new(display, Interest::READ, Mode::Level),
                |_, display, state| {
                    // Safety: we don't drop the display
                    unsafe {
                        display.get_mut().dispatch_clients(state).unwrap();
                    }
                    let _ = state.display_handle.flush_clients();
                    Ok(PostAction::Continue)
                },
            )
            .unwrap();

        socket_name
    }

    pub fn surface_under(
        &self,
        window_id: AutoWindowId,
        pos: Point<f64, Logical>,
    ) -> Option<(WlSurface, Point<f64, Logical>)> {
        self.windows
            .get(window_id)?
            .space()
            .element_under(pos)
            .and_then(|(window, location)| {
                window
                    .surface_under(pos - location.to_f64(), WindowSurfaceType::ALL)
                    .map(|(s, p)| (s, (p + location).to_f64()))
            })
    }

    pub fn element_under(
        &self,
        window_id: AutoWindowId,
        pos: Point<f64, Logical>,
    ) -> Option<Window> {
        self.windows
            .get(window_id)?
            .space()
            .element_under(pos)
            .map(|(window, _)| window.clone())
    }

    pub fn window_space(&self, window_id: AutoWindowId) -> Option<&Space<Window>> {
        self.windows.get(window_id).map(|window| window.space())
    }

    pub fn element_geometry_for_window(
        &self,
        window_id: AutoWindowId,
        window: &Window,
    ) -> Option<Rectangle<i32, Logical>> {
        self.windows
            .get(window_id)?
            .space()
            .element_geometry(window)
    }

    pub fn refresh_window_space(&mut self, window_id: AutoWindowId) {
        if let Some(window) = self.windows.get_mut(window_id) {
            window.space_mut().refresh();
        }
    }

    pub fn set_host_window_requester(&mut self, requester: HostWindowRequester) {
        self.host_window_requester = Some(requester);
    }

    pub fn clear_command_queue(&mut self) {
        self.control_queue.clear();
        self.next_control_action_at = None;
    }

    pub fn has_pending_control_actions(&self) -> bool {
        !self.control_queue.is_empty() || self.next_control_action_at.is_some()
    }

    pub fn begin_control_response(&mut self) -> ControlResponseHandle {
        self.control_responses.begin()
    }

    pub fn complete_control_response(
        &mut self,
        handle: ControlResponseHandle,
        response: ControlResponse,
    ) {
        self.delivered_control_responses.remove(&handle);
        self.control_responses.complete(handle, response);
    }

    pub fn note_control_response_delivered(&mut self, handle: ControlResponseHandle) {
        self.delivered_control_responses.insert(handle);
    }

    pub fn flush_control_responses(&mut self) {
        while let Some(response) = self.control_responses.pop_ready() {
            self.protocol.send_response(&response);
        }
    }

    pub fn fail_control_actions_for_window(&mut self, window_id: AutoWindowId, error: String) {
        let mut failed = HashSet::new();
        let delivered = self.delivered_control_responses.clone();
        self.control_queue.retain(|action| {
            if action.window_id != window_id {
                true
            } else if delivered.contains(&action.response) {
                !action.kind.requires_live_window()
            } else {
                failed.insert(action.response);
                false
            }
        });
        self.pending_screenshots.retain(|request| {
            if request.window_id == window_id {
                failed.insert(request.response);
                false
            } else {
                true
            }
        });

        for handle in failed {
            self.complete_control_response(handle, ControlResponse::Error(error.clone()));
        }
        self.flush_control_responses();
    }

    pub fn presentation_viewport(&self, window_id: AutoWindowId) -> Rectangle<i32, Physical> {
        let host_size = self.window_host_size(window_id);
        if host_size.w <= 0 || host_size.h <= 0 {
            return Rectangle::from_size((0, 0).into());
        }

        let virtual_size = self.window_virtual_size(window_id);
        let scale_x = host_size.w as f64 / virtual_size.w as f64;
        let scale_y = host_size.h as f64 / virtual_size.h as f64;
        let scale = scale_x.min(scale_y);

        let width = (virtual_size.w as f64 * scale).round() as i32;
        let height = (virtual_size.h as f64 * scale).round() as i32;
        let x = (host_size.w - width) / 2;
        let y = (host_size.h - height) / 2;

        Rectangle::new((x, y).into(), (width, height).into())
    }

    pub fn host_to_virtual(
        &self,
        window_id: AutoWindowId,
        pos: Point<f64, Physical>,
    ) -> Option<Point<f64, Logical>> {
        let viewport = self.presentation_viewport(window_id);
        if viewport.size.w <= 0 || viewport.size.h <= 0 {
            return None;
        }

        let x = pos.x - viewport.loc.x as f64;
        let y = pos.y - viewport.loc.y as f64;
        if x < 0.0 || y < 0.0 || x >= viewport.size.w as f64 || y >= viewport.size.h as f64 {
            return None;
        }

        let virtual_size = self.window_virtual_size(window_id);
        let scale_x = viewport.size.w as f64 / virtual_size.w as f64;
        let scale_y = viewport.size.h as f64 / virtual_size.h as f64;
        Some(Point::from((x / scale_x, y / scale_y)))
    }

    pub fn window_geometry(&self, window_id: AutoWindowId) -> WindowGeometry {
        self.windows
            .get(window_id)
            .map(|window| *window.geometry())
            .unwrap_or_else(|| WindowGeometry::new(WindowSizing::Dynamic))
    }

    pub fn window_sizing(&self, window_id: AutoWindowId) -> WindowSizing {
        self.window_geometry(window_id).sizing()
    }

    pub fn window_is_fixed(&self, window_id: AutoWindowId) -> bool {
        self.window_geometry(window_id).is_fixed()
    }

    pub fn virtual_size_for_host_resize(
        &self,
        window_id: AutoWindowId,
        host_size: Size<i32, Physical>,
        host_scale_factor: f64,
    ) -> Size<i32, Logical> {
        self.window_geometry(window_id)
            .virtual_size_for_host(host_size, host_scale_factor)
    }

    pub fn output_mode_for_window(
        &self,
        window_id: AutoWindowId,
        host_size: Size<i32, Physical>,
        virtual_size: Size<i32, Logical>,
        output_scale: f64,
    ) -> (Size<i32, Physical>, f64) {
        self.window_geometry(window_id)
            .output_mode(host_size, virtual_size, output_scale)
    }

    pub fn final_pass_logical_size(
        &self,
        window_id: AutoWindowId,
        host_size: Size<i32, Physical>,
        virtual_size: Size<i32, Logical>,
    ) -> Size<i32, Logical> {
        self.window_geometry(window_id)
            .final_pass_logical_size(host_size, virtual_size)
    }

    pub fn map_new_toplevel(&mut self, window: Window) {
        let window_id = self.windows.create_window();
        info!(?window_id, "new toplevel");
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .set_geometry(WindowGeometry::new(WindowSizing::Dynamic));
        self.create_output_for_window(window_id);

        self.configure_probe(&window);
        window.toplevel().unwrap().send_configure();
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .set_primary_window(window.clone());
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .set_state(AutoWindowState::WaitingProbeCommit);
        self.note_window_alive(window_id);
    }

    pub fn handle_toplevel_commit(&mut self, surface: &WlSurface) {
        let Some(window_id) = self.windows.find_id_by_surface(surface) else {
            return;
        };
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|auto_window| auto_window.primary_window())
            .cloned()
        else {
            return;
        };

        match self
            .windows
            .get(window_id)
            .expect("AutoWC window is missing")
            .state()
        {
            AutoWindowState::WaitingProbeCommit => {
                let preferred_size = self.preferred_toplevel_size(&window);
                if let Some(requester) = &self.host_window_requester {
                    debug!(?window_id, ?preferred_size, "requesting host window");
                    requester.create_window(window_id, preferred_size);
                    self.windows
                        .get_mut(window_id)
                        .expect("AutoWC window is missing")
                        .set_state(AutoWindowState::WaitingHostWindow);
                } else {
                    error!(
                        ?window_id,
                        "cannot create host window because winit backend is not initialized"
                    );
                }
            }
            AutoWindowState::WaitingFinalCommit => {
                debug!(?window_id, "received final toplevel commit");
                self.map_configured_window(window_id);
            }
            AutoWindowState::Mapped => {
                if self
                    .windows
                    .get(window_id)
                    .expect("AutoWC window is missing")
                    .find_overlay_by_surface(surface)
                    .is_some()
                {
                    trace!(?window_id, "recentering overlay after commit");
                    self.center_overlay(window_id, &window);
                }
            }
            AutoWindowState::Empty | AutoWindowState::WaitingHostWindow => {}
        }
    }

    pub fn bind_host_window(
        &mut self,
        window_id: AutoWindowId,
        host_window_id: HostWindowId,
        host_size: Size<i32, Physical>,
        virtual_size: Size<i32, Logical>,
        host_scale_factor: f64,
        output_scale: f64,
        fullscreen: bool,
    ) {
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|auto_window| auto_window.primary_window())
            .cloned()
        else {
            return;
        };

        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .set_host_window(
                host_window_id,
                host_size,
                virtual_size,
                host_scale_factor,
                fullscreen,
            );
        info!(
            ?window_id,
            ?host_window_id,
            ?host_size,
            ?virtual_size,
            host_scale_factor,
            output_scale,
            fullscreen,
            "bound host window"
        );
        self.update_window_output(window_id, host_size, virtual_size, output_scale);

        if self.preferred_toplevel_size(&window) == virtual_size {
            self.configure_toplevel(&window, virtual_size, fullscreen);
            window.toplevel().unwrap().send_pending_configure();
            self.map_configured_window(window_id);
        } else {
            self.configure_toplevel(&window, virtual_size, fullscreen);
            window.toplevel().unwrap().send_pending_configure();
            self.windows
                .get_mut(window_id)
                .expect("AutoWC window is missing")
                .set_state(AutoWindowState::WaitingFinalCommit);
        }
    }

    pub fn resize_window_host(
        &mut self,
        window_id: AutoWindowId,
        host_size: Size<i32, Physical>,
        virtual_size: Size<i32, Logical>,
        host_scale_factor: f64,
        output_scale: f64,
        fullscreen: bool,
    ) {
        if host_size.w <= 0 || host_size.h <= 0 || virtual_size.w <= 0 || virtual_size.h <= 0 {
            warn!(
                ?window_id,
                ?host_size,
                ?virtual_size,
                "ignoring invalid window resize"
            );
            return;
        }
        debug!(
            ?window_id,
            ?host_size,
            ?virtual_size,
            host_scale_factor,
            output_scale,
            fullscreen,
            "resizing window"
        );
        let auto_window = self
            .windows
            .get_mut(window_id)
            .expect("AutoWC window is missing");
        auto_window.set_host_geometry(host_size, host_scale_factor);
        auto_window.set_virtual_size(virtual_size);
        auto_window.set_host_fullscreen(fullscreen);
        self.update_window_output(window_id, host_size, virtual_size, output_scale);
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|auto_window| auto_window.primary_window())
            .cloned()
        else {
            return;
        };
        self.configure_toplevel(&window, virtual_size, fullscreen);
        let toplevel = window.toplevel().unwrap();
        if toplevel.is_initial_configure_sent() {
            toplevel.send_pending_configure();
        }
    }

    pub fn set_window_host_fullscreen(&mut self, window_id: AutoWindowId, fullscreen: bool) {
        let changed = self
            .windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .set_host_fullscreen(fullscreen);
        if !changed {
            return;
        }

        let virtual_size = self.window_virtual_size(window_id);
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|auto_window| auto_window.primary_window())
            .cloned()
        else {
            return;
        };

        info!(?window_id, fullscreen, "updating client fullscreen state");
        self.configure_toplevel(&window, virtual_size, fullscreen);
        let toplevel = window.toplevel().unwrap();
        if toplevel.is_initial_configure_sent() {
            toplevel.send_pending_configure();
        }
    }

    pub fn remove_toplevel(&mut self, surface: &WlSurface) {
        let Some(window_id) = self.windows.find_id_by_surface(surface) else {
            debug!("toplevel destroyed for unknown surface");
            self.maybe_exit_when_empty();
            return;
        };
        let primary_matches = self
            .windows
            .get(window_id)
            .and_then(|window| window.primary_window())
            .is_some_and(|window| window.toplevel().unwrap().wl_surface() == surface);

        if primary_matches {
            info!(?window_id, "primary toplevel removed");
            if let Some(window) = self
                .windows
                .get_mut(window_id)
                .expect("AutoWC window is missing")
                .take_primary_window()
            {
                self.windows
                    .get_mut(window_id)
                    .expect("AutoWC window is missing")
                    .space_mut()
                    .unmap_elem(&window);
            }
            if let Some(host_window_id) = self
                .windows
                .get(window_id)
                .and_then(|window| window.host_window_id())
            {
                if let Some(requester) = &self.host_window_requester {
                    requester.close_window(host_window_id);
                }
            }
            self.promote_overlay(window_id);
            self.refresh_first_alive_window();
            if self
                .windows
                .get(window_id)
                .is_none_or(|window| window.is_empty())
            {
                self.fail_control_actions_for_window(
                    window_id,
                    format!("unknown window: {}", window_id.raw()),
                );
            }
            self.maybe_exit_when_empty();
            return;
        }

        if let Some(window) = self
            .windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .remove_overlay_by_surface(surface)
        {
            debug!(?window_id, "overlay toplevel removed");
            self.windows
                .get_mut(window_id)
                .expect("AutoWC window is missing")
                .space_mut()
                .unmap_elem(&window);
            let next_focus = self
                .windows
                .get(window_id)
                .expect("AutoWC window is missing")
                .next_focus_window();
            self.focus_window(window_id, next_focus.as_ref());
        }

        self.refresh_first_alive_window();
        self.maybe_exit_when_empty();
    }

    pub fn reap_child_processes(&mut self) {
        self.process_pending_clipboard_sync();
        self.reap_clipboard_sync_threads();
        if self.reap_launched_children() {
            self.maybe_exit_when_empty();
        }
    }

    pub fn launch_child(&mut self, command: &[OsString]) -> Result<(), String> {
        let Some((program, args)) = command.split_first() else {
            return Err("missing launch command".into());
        };

        let program_name = program.to_string_lossy();
        info!(program = %program_name, arg_count = args.len(), "launching child process");
        let mut command = Command::new(program);
        configure_child_environment(&mut command, &self.socket_name);
        let child = command
            .args(args)
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .map_err(|err| {
                error!(program = %program_name, error = %err, "failed to launch child process");
                format!("failed to launch {program_name}: {err}")
            })?;
        self.launched_children.push(child);
        if self.reap_launched_children() {
            self.maybe_exit_when_empty();
        }
        Ok(())
    }

    fn reap_launched_children(&mut self) -> bool {
        reap_launched_children(&mut self.launched_children)
    }

    fn terminate_launched_children(&mut self) {
        terminate_launched_children(&mut self.launched_children);
    }

    pub fn configure_probe(&self, window: &Window) {
        let toplevel = window.toplevel().unwrap();
        toplevel.with_pending_state(|state| {
            state.states.unset(xdg_toplevel::State::Fullscreen);
            state.states.unset(xdg_toplevel::State::TiledLeft);
            state.states.unset(xdg_toplevel::State::TiledRight);
            state.states.unset(xdg_toplevel::State::TiledTop);
            state.states.unset(xdg_toplevel::State::TiledBottom);
            state.size = None;
        });
    }

    pub fn configure_toplevel(&self, window: &Window, size: Size<i32, Logical>, fullscreen: bool) {
        let toplevel = window.toplevel().unwrap();
        toplevel.with_pending_state(|state| {
            if fullscreen {
                state.states.set(xdg_toplevel::State::Fullscreen);
                state.states.unset(xdg_toplevel::State::TiledLeft);
                state.states.unset(xdg_toplevel::State::TiledRight);
                state.states.unset(xdg_toplevel::State::TiledTop);
                state.states.unset(xdg_toplevel::State::TiledBottom);
            } else {
                state.states.unset(xdg_toplevel::State::Fullscreen);
                state.states.set(xdg_toplevel::State::TiledLeft);
                state.states.set(xdg_toplevel::State::TiledRight);
                state.states.set(xdg_toplevel::State::TiledTop);
                state.states.set(xdg_toplevel::State::TiledBottom);
            }
            state.size = Some(size);
        });
    }

    pub fn focus_window(&mut self, window_id: AutoWindowId, window: Option<&Window>) {
        let surface = window.map(|window| window.toplevel().unwrap().wl_surface().clone());
        let serial = SERIAL_COUNTER.next_serial();

        if let Some(window) = window {
            self.windows
                .get_mut(window_id)
                .expect("AutoWC window is missing")
                .space_mut()
                .raise_element(window, true);
        }

        for window in self.mapped_windows() {
            let toplevel = window.toplevel().unwrap();
            let activated = surface
                .as_ref()
                .is_some_and(|surface| toplevel.wl_surface() == surface);
            if window.set_activated(activated) && toplevel.is_initial_configure_sent() {
                toplevel.send_pending_configure();
            }
        }

        self.focused_window_id = surface.as_ref().map(|_| window_id);
        let keyboard = self.seat.get_keyboard().unwrap();
        keyboard.set_focus(self, surface, serial);
    }

    pub fn focus_auto_window(&mut self, window_id: AutoWindowId) {
        let window = self
            .windows
            .get(window_id)
            .and_then(|window| window.next_focus_window());
        self.focus_window(window_id, window.as_ref());
    }

    fn focus_initial_auto_window(&mut self, window_id: AutoWindowId) {
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|window| window.next_focus_window())
        else {
            self.focus_window(window_id, None);
            return;
        };
        let surface = window.toplevel().unwrap().wl_surface().clone();

        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .space_mut()
            .raise_element(&window, true);

        // HACK: Some clients (Chromium) ignore the first keyboard enter for a
        // newly mapped nested toplevel. Force a keyboard leave/enter cycle for
        // initial focus only, without toggling xdg activation. This should
        // probably be correctly fixed at some point.
        let keyboard = self.seat.get_keyboard().unwrap();
        self.focused_window_id = Some(window_id);
        keyboard.set_focus(self, Some(surface.clone()), SERIAL_COUNTER.next_serial());
        self.focused_window_id = None;
        keyboard.set_focus(self, None, SERIAL_COUNTER.next_serial());
        self.focused_window_id = Some(window_id);
        keyboard.set_focus(self, Some(surface.clone()), SERIAL_COUNTER.next_serial());

        for window in self.mapped_windows() {
            let toplevel = window.toplevel().unwrap();
            let activated = toplevel.wl_surface() == &surface;
            if window.set_activated(activated) && toplevel.is_initial_configure_sent() {
                toplevel.send_pending_configure();
            }
        }
    }

    pub fn blur_auto_window(&mut self, window_id: AutoWindowId) {
        if self.focused_window_id == Some(window_id) {
            self.focus_window(window_id, None);
        }
    }

    pub fn queue_screenshot(
        &mut self,
        window_id: AutoWindowId,
        path: Option<PathBuf>,
        response: ControlResponseHandle,
    ) {
        let path = match path {
            Some(path) => path,
            None => {
                let path = self.next_screenshot_path();
                self.autogenerated_screenshots.push(path.clone());
                path
            }
        };
        debug!(?window_id, path = %path.display(), "queued screenshot");
        self.pending_screenshots.push_back(ScreenshotRequest {
            window_id,
            path,
            response,
        });
    }

    pub fn request_shutdown(&mut self) {
        info!("shutdown requested");
        self.terminate_launched_children();
        self.cleanup_autogenerated_screenshots();
        self.loop_signal.stop();
    }

    fn cleanup_autogenerated_screenshots(&mut self) {
        cleanup_screenshot_paths(self.autogenerated_screenshots.drain(..));
    }

    fn next_screenshot_path(&mut self) -> PathBuf {
        let pid = std::process::id();

        loop {
            self.screenshot_counter += 1;
            let path = std::env::temp_dir().join(format!(
                "autowc-screenshot-{pid}-{}.png",
                self.screenshot_counter
            ));
            if !path.exists() {
                return path;
            }
        }
    }

    fn promote_overlay(&mut self, window_id: AutoWindowId) {
        let Some(window) = self
            .windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .promote_last_overlay()
        else {
            self.focus_window(window_id, None);
            return;
        };

        let virtual_size = self.window_virtual_size(window_id);
        let fullscreen = self
            .windows
            .get(window_id)
            .expect("AutoWC window is missing")
            .host_fullscreen();
        self.configure_toplevel(&window, virtual_size, fullscreen);
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .space_mut()
            .map_element(window.clone(), (0, 0), false);
        self.focus_window(window_id, Some(&window));

        let overlays = self.overlay_windows(window_id);
        for overlay in overlays {
            self.center_overlay(window_id, &overlay);
        }
    }

    pub fn mapped_windows_for(&self, window_id: AutoWindowId) -> Vec<Window> {
        self.windows
            .get(window_id)
            .map(|window| window.mapped_windows())
            .unwrap_or_default()
    }

    pub fn mapped_windows(&self) -> Vec<Window> {
        self.windows.mapped_windows()
    }

    pub fn mapped_window_ids(&self) -> Vec<AutoWindowId> {
        self.windows.mapped_ids()
    }

    pub fn window_info(&self, window_id: AutoWindowId) -> Option<WindowInfo> {
        let window = self.windows.get(window_id)?.primary_window()?;
        let size = self.window_virtual_size(window_id);
        let surface = window.toplevel().unwrap().wl_surface();
        let title = with_states(surface, |states| {
            states
                .data_map
                .get::<XdgToplevelSurfaceData>()
                .and_then(|data| data.lock().unwrap().title.clone())
                .unwrap_or_default()
        });
        Some(WindowInfo {
            id: window_id.raw(),
            title,
            width: size.w,
            height: size.h,
        })
    }

    pub fn window_infos(&self) -> Vec<WindowInfo> {
        let mut windows = self
            .mapped_window_ids()
            .into_iter()
            .filter_map(|window_id| self.window_info(window_id))
            .collect::<Vec<_>>();
        windows.sort_by_key(|window| window.id);
        windows
    }

    fn overlay_windows(&self, window_id: AutoWindowId) -> Vec<Window> {
        self.windows
            .get(window_id)
            .map(|window| window.overlay_windows().cloned().collect())
            .unwrap_or_default()
    }

    fn maybe_exit_when_empty(&mut self) {
        if !self.stay_alive && self.windows.is_empty() {
            self.request_shutdown();
        }
    }

    fn note_window_alive(&mut self, window_id: AutoWindowId) {
        self.first_alive_window_id = Some(match self.first_alive_window_id {
            Some(first_alive_window_id) if first_alive_window_id.raw() < window_id.raw() => {
                first_alive_window_id
            }
            _ => window_id,
        });
        trace!(?window_id, first_alive_window_id = ?self.first_alive_window_id, "recorded live window");
    }

    fn refresh_first_alive_window(&mut self) {
        self.first_alive_window_id = self.windows.first_alive_id();
    }

    fn window_host_size(&self, window_id: AutoWindowId) -> Size<i32, Physical> {
        self.windows
            .get(window_id)
            .and_then(|window| window.host_size())
            .unwrap_or_else(|| self.initial_virtual_size.to_physical(1))
    }

    pub fn find_window_by_host_window(&self, host_window_id: HostWindowId) -> Option<AutoWindowId> {
        self.windows.find_id_by_host_window(host_window_id)
    }

    pub fn close_host_window(&mut self, host_window_id: HostWindowId) {
        let Some(window_id) = self.find_window_by_host_window(host_window_id) else {
            warn!(?host_window_id, "close requested for unknown host window");
            return;
        };
        if let Err(err) = self.close_auto_window(window_id) {
            warn!(?window_id, error = %err, "failed to close requested host window");
        }
    }

    pub fn close_auto_window(&self, window_id: AutoWindowId) -> Result<(), String> {
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|window| window.primary_window())
        else {
            return Err(format!("unknown window: {}", window_id.raw()));
        };
        info!(?window_id, "sending close to client toplevel");
        window.toplevel().unwrap().send_close();
        Ok(())
    }

    pub fn request_host_fullscreen(&self, surface: &WlSurface, fullscreen: bool) {
        let Some(window_id) = self.windows.find_id_by_surface(surface) else {
            warn!(fullscreen, "fullscreen request for unknown client toplevel");
            return;
        };
        let Some(host_window_id) = self
            .windows
            .get(window_id)
            .and_then(|window| window.host_window_id())
        else {
            warn!(
                ?window_id,
                fullscreen, "fullscreen request before host window exists"
            );
            return;
        };
        let Some(requester) = &self.host_window_requester else {
            warn!(
                ?window_id,
                fullscreen, "cannot request host fullscreen without host backend"
            );
            return;
        };

        info!(
            ?window_id,
            ?host_window_id,
            fullscreen,
            "requesting host fullscreen"
        );
        requester.set_fullscreen(host_window_id, fullscreen);
    }

    fn map_configured_window(&mut self, window_id: AutoWindowId) {
        let Some(window) = self
            .windows
            .get(window_id)
            .and_then(|auto_window| auto_window.primary_window())
            .cloned()
        else {
            return;
        };
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .space_mut()
            .map_element(window.clone(), (0, 0), false);
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .set_state(AutoWindowState::Mapped);
        info!(?window_id, "mapped toplevel");
        self.focus_initial_auto_window(window_id);
    }

    fn preferred_toplevel_size(&self, window: &Window) -> Size<i32, Logical> {
        let size = window.geometry().size;
        if size.w > 0 && size.h > 0 {
            size
        } else {
            self.initial_virtual_size
        }
    }

    fn center_overlay(&mut self, window_id: AutoWindowId, window: &Window) {
        let geometry = window.geometry();
        if geometry.size.w <= 0 || geometry.size.h <= 0 {
            return;
        }

        let virtual_size = self.window_virtual_size(window_id);
        // TODO: Replace this with a real overlay policy. This should eventually
        // consider xdg parent/transient relationships and clamp to the output.
        let x = ((virtual_size.w - geometry.size.w) / 2).max(0);
        let y = ((virtual_size.h - geometry.size.h) / 2).max(0);
        self.windows
            .get_mut(window_id)
            .expect("AutoWC window is missing")
            .space_mut()
            .map_element(window.clone(), (x, y), false);
    }
}

fn configure_child_environment(command: &mut Command, socket_name: &OsString) {
    command
        .env("WAYLAND_DISPLAY", socket_name)
        .env_remove("DISPLAY");
}

fn reap_launched_children(children: &mut Vec<Child>) -> bool {
    let mut reaped = false;
    children.retain_mut(|child| match child.try_wait() {
        Ok(Some(status)) => {
            info!(%status, "launched child exited");
            reaped = true;
            false
        }
        Ok(None) => true,
        Err(err) => {
            error!(error = %err, "failed to poll launched child process");
            reaped = true;
            false
        }
    });
    reaped
}

fn terminate_launched_children(children: &mut Vec<Child>) {
    if children.is_empty() {
        return;
    }

    reap_launched_children(children);
    if children.is_empty() {
        return;
    }

    info!(
        child_count = children.len(),
        "terminating launched child processes"
    );
    for child in children.iter_mut() {
        send_sigterm(child);
    }

    wait_for_children(children, CHILD_TERMINATION_GRACE_PERIOD);
    if children.is_empty() {
        return;
    }

    warn!(
        child_count = children.len(),
        "launched child processes did not exit after SIGTERM; killing"
    );
    kill_children(children);
    wait_for_children(children, CHILD_KILL_GRACE_PERIOD);
    if !children.is_empty() {
        warn!(
            child_count = children.len(),
            "launched child processes remained live after SIGKILL"
        );
    }
}

fn send_sigterm(child: &mut Child) {
    let pid = child.id();
    let result = unsafe { libc::kill(pid as libc::pid_t, libc::SIGTERM) };
    if result == 0 {
        debug!(pid, "sent SIGTERM to launched child process");
    } else {
        let err = std::io::Error::last_os_error();
        warn!(pid, error = %err, "failed to send SIGTERM to launched child process");
    }
}

fn kill_children(children: &mut Vec<Child>) {
    for child in children.iter_mut() {
        let pid = child.id();
        match child.kill() {
            Ok(()) => debug!(pid, "sent SIGKILL to launched child process"),
            Err(err) => warn!(pid, error = %err, "failed to kill launched child process"),
        }
    }
}

fn wait_for_children(children: &mut Vec<Child>, timeout: Duration) {
    let deadline = Instant::now() + timeout;
    while !children.is_empty() {
        reap_launched_children(children);
        if children.is_empty() {
            return;
        }

        let remaining = deadline.saturating_duration_since(Instant::now());
        if remaining.is_zero() {
            return;
        }

        std::thread::sleep(remaining.min(CHILD_TERMINATION_POLL_INTERVAL));
    }
}

fn cleanup_screenshot_paths(paths: impl IntoIterator<Item = PathBuf>) {
    for path in paths {
        match std::fs::remove_file(&path) {
            Ok(()) => {}
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(err) => warn!(
                path = %path.display(),
                error = %err,
                "failed to remove autogenerated screenshot"
            ),
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct TimingOptions {
    pub key_event_interval: Duration,
    pub chord_key_interval: Duration,
    pub chord_hold_duration: Duration,
    pub command_interval: Duration,
}

impl Default for TimingOptions {
    fn default() -> Self {
        Self {
            key_event_interval: crate::input::DEFAULT_KEY_EVENT_INTERVAL,
            chord_key_interval: crate::input::DEFAULT_CHORD_KEY_INTERVAL,
            chord_hold_duration: crate::input::DEFAULT_CHORD_HOLD_DURATION,
            command_interval: crate::input::DEFAULT_COMMAND_INTERVAL,
        }
    }
}

/// Data associated with a wayland client that connects to AutoWC.
/// One instance of this type per client.
#[derive(Default)]
pub struct ClientState {
    pub compositor_state: CompositorClientState,
}

pub struct ScreenshotRequest {
    pub window_id: AutoWindowId,
    pub path: PathBuf,
    pub response: ControlResponseHandle,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ControlResponseHandle(u64);

#[derive(Debug, Default)]
pub struct ControlResponseQueue {
    next_id: u64,
    pending: VecDeque<PendingControlResponse>,
}

#[derive(Debug)]
struct PendingControlResponse {
    handle: ControlResponseHandle,
    response: Option<ControlResponse>,
}

impl ControlResponseQueue {
    pub fn begin(&mut self) -> ControlResponseHandle {
        self.next_id += 1;
        let handle = ControlResponseHandle(self.next_id);
        self.pending.push_back(PendingControlResponse {
            handle,
            response: None,
        });
        handle
    }

    pub fn complete(&mut self, handle: ControlResponseHandle, response: ControlResponse) {
        let Some(pending) = self
            .pending
            .iter_mut()
            .find(|pending| pending.handle == handle)
        else {
            warn!(?handle, "cannot complete unknown control response");
            return;
        };

        if pending.response.is_some() {
            warn!(?handle, "control response already completed");
            return;
        }

        pending.response = Some(response);
    }

    pub fn pop_ready(&mut self) -> Option<ControlResponse> {
        let response = self.pending.front_mut()?.response.take()?;
        self.pending.pop_front();
        Some(response)
    }
}

#[derive(Debug)]
pub struct QueuedControlAction {
    pub window_id: AutoWindowId,
    pub response: ControlResponseHandle,
    pub kind: QueuedControlActionKind,
}

#[derive(Debug)]
pub enum QueuedControlActionKind {
    Key {
        code: u32,
        state: KeyState,
    },
    PointerMove {
        x: f64,
        y: f64,
    },
    PointerButton {
        button: u32,
        state: ButtonState,
    },
    Scroll {
        dx_axis: f64,
        dy_axis: f64,
        dx_v120: i32,
        dy_v120: i32,
    },
    Screenshot {
        path: Option<PathBuf>,
        delay_after: Duration,
    },
    Close,
    Delay(Duration),
    Respond {
        response: ControlResponse,
        delay_after: Duration,
    },
}

impl QueuedControlActionKind {
    pub fn requires_live_window(&self) -> bool {
        !matches!(self, Self::Delay(_) | Self::Respond { .. })
    }

    pub fn delivers_to_window(&self) -> bool {
        matches!(
            self,
            Self::Key { .. }
                | Self::PointerMove { .. }
                | Self::PointerButton { .. }
                | Self::Scroll { .. }
        )
    }
}

impl ClientData for ClientState {
    fn initialized(&self, client_id: ClientId) {
        debug!(?client_id, "nested wayland client initialized");
    }

    fn disconnected(&self, client_id: ClientId, reason: DisconnectReason) {
        info!(?client_id, ?reason, "nested wayland client disconnected");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn control_response_queue_flushes_ready_responses_in_order() {
        let mut queue = ControlResponseQueue::default();
        let first = queue.begin();
        let second = queue.begin();

        queue.complete(second, ControlResponse::Ok);
        assert!(queue.pop_ready().is_none());

        queue.complete(first, ControlResponse::Error("first failed".to_string()));
        assert_eq!(
            queue.pop_ready(),
            Some(ControlResponse::Error("first failed".to_string()))
        );
        assert_eq!(queue.pop_ready(), Some(ControlResponse::Ok));
        assert!(queue.pop_ready().is_none());
    }

    #[test]
    fn cleanup_screenshot_paths_removes_existing_files_and_ignores_missing_files() {
        let pid = std::process::id();
        let path = std::env::temp_dir().join(format!("autowc-cleanup-test-{pid}.png"));
        let missing_path = std::env::temp_dir().join(format!("autowc-cleanup-missing-{pid}.png"));

        std::fs::write(&path, b"test").unwrap();
        let _ = std::fs::remove_file(&missing_path);

        cleanup_screenshot_paths([path.clone(), missing_path]);

        assert!(!path.exists());
    }

    #[test]
    fn configure_child_environment_sets_wayland_display_and_unsets_display() {
        let socket_name = OsString::from("wayland-autowc-test");
        let mut command = Command::new("true");

        configure_child_environment(&mut command, &socket_name);

        let envs: HashMap<_, _> = command.get_envs().collect();
        assert_eq!(
            envs.get(std::ffi::OsStr::new("WAYLAND_DISPLAY")),
            Some(&Some(std::ffi::OsStr::new("wayland-autowc-test")))
        );
        assert_eq!(envs.get(std::ffi::OsStr::new("DISPLAY")), Some(&None));
    }

    #[test]
    fn terminate_launched_children_terminates_and_reaps_live_children() {
        let child = Command::new("sleep").arg("60").spawn().unwrap();
        let mut children = vec![child];

        terminate_launched_children(&mut children);

        assert!(children.is_empty());
    }
}
